### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by Swati002** [zabihhaqqani/Banana-Speak#13]
Assign this issue to me

**Comment by zabihhaqqani** [comment]
sure go ahead

assigned it to you!

**Comment by zabihhaqqani** [comment]
It would be great if you could add these in the footer

https://github.com/zabihhaqqani
https://www.linkedin.com/in/zabih-haqqani-7ab187191/
https://twitter.com/zabih01

**Comment by hasnainabeel** [comment]
Assign me @zabihhaqqani

**Comment by zabihhaqqani** [comment]
sure go ahead
