### ISSUE TITLE
Add a button to Speak up the translated text . 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [zabihhaqqani/Banana-Speak#17]
I want to add a button which will speak up the result . it would be helpful if someone wants to listen the output .  Can you assign it to me .

**Comment by AjayMaheshwari23** [comment]
@zabihhaqqani

**Comment by zabihhaqqani** [comment]
That's a great idea, @AjayMaheshwari23 it would be a great feature.

go ahead, assigned it to you.
