### ISSUE TITLE
inpute dark mood

### ISSUE THREAD

**Issue by AnasMansy** [zabihhaqqani/Banana-Speak#33]
on dark mood inputs  still light
 
can i work on this

**Comment by zabihhaqqani** [comment]
can you elaborate?

**Comment by AnasMansy** [comment]
in dark mood inputs still white
![bef](https://user-images.githubusercontent.com/91702503/194719724-baa06823-f927-4e20-9d29-5e1a266abba0.JPG)
i want to update them to 
![afte](https://user-images.githubusercontent.com/91702503/194719764-97c4f6f7-29f7-488d-a701-38701032cd21.JPG)
to

**Comment by zabihhaqqani** [comment]
I made it white as it was better.

didn't like black

**Comment by AnasMansy** [comment]
ok  any recommendation for another issue
